

<div class="address">
    <div class="holder">
        
            <ul class="footerinfo">
                <li>
                    <span class="h3">YOUR Company</span>
                    <h5 class="address">
                        <address>
                            <p>Business Company Standard, Musterstrasse 10, 6300 Zug</p><dl><dt class='icon icon-phone'><span class='label'>Phone</span></dt><dd>+49 041 XXX</dd><dt class='icon icon-phone3'><span class='label'>Fax</span></dt><dd>+49 041 YYY</dd></dl>
                        </address>
                    </h5>
                </li>
                <li id="AddThisButton" class="AddThis">
                    
                    <!-- AddThis Toolbox BEGIN -->
                    <div class="addthis_toolbox addthis_default_style ">
                    <a href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=ra-4d67543c405d9864" class="addthis_button_compact">weiterleiten</a>
                    <span class="addthis_separator">|</span>
                    <a class="addthis_button_preferred_1"></a>
                    <a class="addthis_button_preferred_2"></a>
                    <a class="addthis_button_preferred_3"></a>
                    <a class="addthis_button_preferred_4"></a>
                    </div>
                    <script type="text/javascript">var addthis_config = {"data_track_clickback":true};</script>
                    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=ra-4d67543c405d9864"></script>
                    <!-- AddThis Toolbox END -->
                    </li>
            </ul>
                  
    </div>
</div>
<!--
<div class="footer">
    <div class="holder">
        <a title="nach oben" href="" rel="nofollow" class="top">nach oben</a> 
        <ul class="hilfsnavi" id="hilfsnavi">
            <li><p>&copy; insyma</p></li>
            
                    <li><a href="/CU_BusinessCompanyStandard/eng/impressum_23442.shtml" title="Impressum">Impressum</a></li>       
                
        </ul>
    </div>
</div>
-->
