
	<div class="con-footer-address">
		<ul>
			<li>
				<h4 class="h4 item-title">Kontakt</h4>
						<div class="con-address">
							Business Company Standard
							<ul class="list">
								<li>Services f&uuml;r das Internet</li>
								<li id="ctl01_ctl00_street">Musterstrasse 10</li>
								
								<li id="ctl01_ctl00_city">6300 Zug</li>
								<li id="ctl01_ctl00_country">CH Schweiz</li>
								<li><ul class="con-address-contact-options">
										<li><span class='label'><span>Telefon</span></span><span class='value'><a  href="tel:+41000000000" >041 000 99 99</a></span></li>
									
										<li><span class='label'><span>Fax</span></span><span class='value'>041 00 000 99 98</span></li>
									
										<li><span class='label'><span>E-Mail</span></span><span class='value'><a  href="mailto:L_hc__dradnatsynapmocssenisub--liam" >Verlinkung: Link / Mail / Telefonnummer</a></span></li>
									</ul></li>
							</ul>
						</div>
					<div class="hide"><p>&copy; insyma</p></div>
			</li>
		</ul>
	</div>
         


	<div class="con-footer-links">
		<span class="h4 item-title">Linkliste</span><ul class="list list-level-1">
				<li class="item">
					<span class="item-title">Spalte 1</span>
					<ul class="list list-level-2">
							<li class="item">
								<h4 class="item-link"><a href="/CU_BusinessCompanyStandard/deu/aktuelles_23715.shtml" title="Aktuelles">Aktuelles</a></h4>
								
							</li>
						
							<li class="item">
								<h4 class="item-link"><a href="/CU_BusinessCompanyStandard/default.shtml" title="Startseite">Startseite</a></h4>
								
							</li>
						</ul>
				</li>
			
				<li class="item">
					<span class="item-title">Spalte 2</span>
					<ul class="list list-level-2">
							<li class="item">
								<h4 class="item-link"><a href="/CU_BusinessCompanyStandard/deu/sitemap_23356.shtml" title="Sitemap">Sitemap</a></h4>
								
							</li>
						
							<li class="item">
								<h4 class="item-link"><a href="/CU_BusinessCompanyStandard/deu/aktuelles_23715.shtml" title="Aktuelles">Aktuelles</a></h4>
								
							</li>
						</ul>
				</li>
			</ul>


	</div>
          
