
<!-- LANG Scritps -->
<script type="text/javascript" src="http://test.contentupdate.net/CU_BusinessCompanyStandard/deu/insymaOverlaybox.config.js"></script>
<script type="text/javascript">
    var shariff_link = "/CU_BusinessCompanyStandard/deu/impressum_23442.shtml";
    var schariff_socials = ["facebook","linkedin","twitter","xing","info"];
</script>


    <script type="text/javascript" src="http://test.contentupdate.net/CU_BusinessCompanyStandard/js/main.min.js?cache=1603086269757.69"></script>


<script type="text/javascript">
    var MAP_API = "https://maps.google.com/maps/api/js?key=AIzaSyDyzarhJJRrVzoam2IRzssxkIPa0Xh5Z8s";
</script>



<!--[if (gte IE 6)&(lte IE 8)]>
    <script type="text/javascript" src="http://test.contentupdate.net/CU_BusinessCompanyStandard/js/lib/selectivizr-min.js?cache=1603086269757.69"></script>
<![endif]-->
<!-- FAVICON http://www.favicomatic.com/ -->
<link rel="shortcut icon" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon.ico" type="image/x-icon" />
<link rel="apple-touch-icon-precomposed" sizes="57x57" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-57x57.png" />
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-114x114.png" />
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-72x72.png" />
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-144x144.png" />
<link rel="apple-touch-icon-precomposed" sizes="60x60" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-60x60.png" />
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-120x120.png" />
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-76x76.png" />
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/apple-touch-icon-152x152.png" />
<link rel="icon" type="image/png" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon-196x196.png" sizes="196x196" />
<link rel="icon" type="image/png" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/png" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon-32x32.png" sizes="32x32" />
<link rel="icon" type="image/png" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon-16x16.png" sizes="16x16" />
<link rel="icon" type="image/png" href="http://test.contentupdate.net/CU_BusinessCompanyStandard/favicon-128.png" sizes="128x128" />
<meta name="application-name" content='Business Company Standard'/>
<meta name="theme-color" content="#ffffff" />
<meta name="msapplication-TileColor" content="#FFFFFF" />
<meta name="msapplication-TileImage" content="http://test.contentupdate.net/CU_BusinessCompanyStandard/mstile-144x144.png" />
<meta name="msapplication-square70x70logo" content="http://test.contentupdate.net/CU_BusinessCompanyStandard/mstile-70x70.png" />
<meta name="msapplication-square150x150logo" content="http://test.contentupdate.net/CU_BusinessCompanyStandard/mstile-150x150.png" />
<meta name="msapplication-wide310x150logo" content="http://test.contentupdate.net/CU_BusinessCompanyStandard/mstile-310x150.png" />
<meta name="msapplication-square310x310logo" content="http://test.contentupdate.net/CU_BusinessCompanyStandard/mstile-310x310.png" />