
<!-- SCREEN -->
<script type="text/javascript" src="http://www.contentupdate.net/insymaLib/Standard/modernizr/modernizr.full.js"></script>
<script type="text/javascript">window.jQuery || document.write('<script src="http://www.contentupdate.net/insymaLib/Standard/jquery/jquery-1.8.2.min.js" type="text/javascript"><\/script>')</script>
<script type="text/javascript" src="../js/lib/jquery-ui-custom.min.js"></script>
<script type="text/javascript" src="http://www.contentupdate.net/insymaLib/standard/jquerytools/flexslider/jquery.flexslider.js"></script>

<script type="text/javascript" src="../js/insymaFormValidation.js?cache=1378804469326.12"></script>
<script type="text/javascript" src="../deu/insymaOverlaybox.config.js"></script>
<script type="text/javascript" src="../js/insymaOverlaybox.js?cache=1378804469326.12"></script>
<script type="text/javascript" src="../js/project_scripts.js?cache=1378804469326.12"></script>

<!--[if lt IE 9]>
	<script type="text/javascript" src="http://www.contentupdate.net/insymaLib/standard/pie/PIE2/PIE_IE678.js"></script>
<![endif]-->

<!-- FAVICON -->
<link rel="shortcut icon" href="../favicon.ico" />
